spark:
  master: local[*]
  app:
    name: Spring Spark Word Count Application
#  spark.home=%SPARK_HOME%

#  server.port=3000

spring:
  main:
    lazy-initialization: true

logging:
  level:
    root: INFO
    org.apache.spark: WARN
    org.apache.spark.executor: ERROR
    org.elasticsearch.hadoop.rest: ERROR
    org.spark_project.jetty.server: WARN
    org.springframework.web: ERROR
