spark:
  master: local[*]
  app:
    name: Spring Spark Word Count Application
#  spark.home=%SPARK_HOME%

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  server:
    port: 8080
  main:
    lazy-initialization: false
  application:
    name: greet-service
  boot:
    admin:
      client:
        url: http://localhost:${spring.server.port}

logging:
  level:
    root: INFO
    org.apache.spark: WARN
    org.apache.spark.executor: ERROR
    org.elasticsearch.hadoop.rest: ERROR
    org.spark_project.jetty.server: WARN
    org.springframework.web: ERROR
